In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# JUMAN++のインストール（結構，時間かかる）

!wget https://github.com/ku-nlp/jumanpp/releases/download/v2.0.0-rc2/jumanpp-2.0.0-rc2.tar.xz && \
tar xJvf jumanpp-2.0.0-rc2.tar.xz && \
rm jumanpp-2.0.0-rc2.tar.xz && \
cd jumanpp-2.0.0-rc2/ && \
mkdir bld && \
cd bld && \
cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr/local && \
make && \
sudo make install

--2022-01-07 07:10:34--  https://github.com/ku-nlp/jumanpp/releases/download/v2.0.0-rc2/jumanpp-2.0.0-rc2.tar.xz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/70542756/4eeea9d6-279f-11e8-8428-a24e7d7d8b99?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220107%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220107T071034Z&X-Amz-Expires=300&X-Amz-Signature=7e17a1ea37de725e9a4c1d0672106b864392733869a6353448cc7d73cb4f9958&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=70542756&response-content-disposition=attachment%3B%20filename%3Djumanpp-2.0.0-rc2.tar.xz&response-content-type=application%2Foctet-stream [following]
--2022-01-07 07:10:34--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/70542756/4eeea9d6-279f-11e8-8428-a24e7d7d8b99?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220107%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220107T071034Z&X-Amz-Expires=300&X-Amz-Signature=7e17a1ea37de725e9a4c1d0672106b864392733869a6353448cc7d73cb4f9958&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=70542756&response-content-disposition=attachment%3B%20filename%3Djumanpp-2.0.0-rc2.tar.xz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 320032952 (305M) [application/octet-stream]
Saving to: ‘jumanpp-2.0.0-rc2.tar.xz’

jumanpp-2.0.0-rc2.t 100%[===================>] 305.21M  17.9MB/s    in 11s

2022-01-07 07:10:45 (27.5 MB/s) - ‘jumanpp-2.0.0-rc2.tar.xz’ saved [320032952/320032952]

jumanpp-2.0.0-rc2/
jumanpp-2.0.0-rc2/CMakeLists.txt
jumanpp-2.0.0-rc2/test/
jumanpp-2.0.0-rc2/docs/
jumanpp-2.0.0-rc2/CONTRIBUTORS
jumanpp-2.0.0-rc2/libs/
jumanpp-2.0.0-rc2/README.md
jumanpp-2.0.0-rc2/model/
jumanpp-2.0.0-rc2/version.cmake
jumanpp-2.0.0-rc2/src/
jumanpp-2.0.0-rc2/src/jumandic/
jumanpp-2.0.0-rc2/src/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/
jumanpp-2.0.0-rc2/src/util/
jumanpp-2.0.0-rc2/src/testing/
jumanpp-2.0.0-rc2/src/rnn/
jumanpp-2.0.0-rc2/src/rnn/simple_rnn_impl.h
jumanpp-2.0.0-rc2/src/rnn/mikolov_rnn.h
jumanpp-2.0.0-rc2/src/rnn/CMakeLists.txt
jumanpp-2.0.0-rc2/src/rnn/mikolov_rnn_impl.h
jumanpp-2.0.0-rc2/src/rnn/mikolov_rnn.cc
jumanpp-2.0.0-rc2/src/rnn/legacy/
jumanpp-2.0.0-rc2/src/rnn/mikolov_rnn_test.cc
jumanpp-2.0.0-rc2/src/rnn/legacy/rnnlmlib_static.cpp
jumanpp-2.0.0-rc2/src/rnn/legacy/rnnlmlib.h
jumanpp-2.0.0-rc2/src/rnn/legacy/rnnlmlib_static.h
jumanpp-2.0.0-rc2/src/testing/CMakeLists.txt
jumanpp-2.0.0-rc2/src/testing/test_config.h.in
jumanpp-2.0.0-rc2/src/testing/catch_main.cc
jumanpp-2.0.0-rc2/src/testing/standalone_test.h
jumanpp-2.0.0-rc2/src/testing/test_analyzer.h
jumanpp-2.0.0-rc2/src/testing/read_file_test.cc
jumanpp-2.0.0-rc2/src/util/coded_io.h
jumanpp-2.0.0-rc2/src/util/memory.cpp
jumanpp-2.0.0-rc2/src/util/stl_util.h
jumanpp-2.0.0-rc2/src/util/codegen.cc
jumanpp-2.0.0-rc2/src/util/printer.h
jumanpp-2.0.0-rc2/src/util/characters.cc
jumanpp-2.0.0-rc2/src/util/mmap.cc
jumanpp-2.0.0-rc2/src/util/debug_output.h
jumanpp-2.0.0-rc2/src/util/fast_hash.h
jumanpp-2.0.0-rc2/src/util/mmap_impl_unix.h
jumanpp-2.0.0-rc2/src/util/string_piece.cc
jumanpp-2.0.0-rc2/src/util/CMakeLists.txt
jumanpp-2.0.0-rc2/src/util/serialization_test.cc
jumanpp-2.0.0-rc2/src/util/logging.cpp
jumanpp-2.0.0-rc2/src/util/array_slice_util_test.cc
jumanpp-2.0.0-rc2/src/util/printer.cc
jumanpp-2.0.0-rc2/src/util/array_slice_test.cc
jumanpp-2.0.0-rc2/src/util/memory_test.cpp
jumanpp-2.0.0-rc2/src/util/status.cpp
jumanpp-2.0.0-rc2/src/util/lru_cache.h
jumanpp-2.0.0-rc2/src/util/serialization.h
jumanpp-2.0.0-rc2/src/util/flatmap.h
jumanpp-2.0.0-rc2/src/util/seahash_test.cc
jumanpp-2.0.0-rc2/src/util/string_piece_test.cc
jumanpp-2.0.0-rc2/src/util/inlined_vector_test.cc
jumanpp-2.0.0-rc2/src/util/quantized_weights.h
jumanpp-2.0.0-rc2/src/util/fast_printer.h
jumanpp-2.0.0-rc2/src/util/string_piece.h
jumanpp-2.0.0-rc2/src/util/win32_utils.cc
jumanpp-2.0.0-rc2/src/util/status_test.cpp
jumanpp-2.0.0-rc2/src/util/inlined_vector.h
jumanpp-2.0.0-rc2/src/util/characters_test.cpp
jumanpp-2.0.0-rc2/src/util/status.hpp
jumanpp-2.0.0-rc2/src/util/codegen.h
jumanpp-2.0.0-rc2/src/util/csv_reader.cc
jumanpp-2.0.0-rc2/src/util/flatrep.h
jumanpp-2.0.0-rc2/src/util/seahash.h
jumanpp-2.0.0-rc2/src/util/csv_reader_test.cc
jumanpp-2.0.0-rc2/src/util/mmap_test.cc
jumanpp-2.0.0-rc2/src/util/coded_io_test.cc
jumanpp-2.0.0-rc2/src/util/lazy_test.cc
jumanpp-2.0.0-rc2/src/util/flatset.h
jumanpp-2.0.0-rc2/src/util/hashing_test.cc
jumanpp-2.0.0-rc2/src/util/assert.cc
jumanpp-2.0.0-rc2/src/util/char_buffer.h
jumanpp-2.0.0-rc2/src/util/printer_test.cc
jumanpp-2.0.0-rc2/src/util/lazy.h
jumanpp-2.0.0-rc2/src/util/stl_util_test.cc
jumanpp-2.0.0-rc2/src/util/fast_hash_test.cc
jumanpp-2.0.0-rc2/src/util/coded_io.cc
jumanpp-2.0.0-rc2/src/util/murmur_hash.h
jumanpp-2.0.0-rc2/src/util/format.cc
jumanpp-2.0.0-rc2/src/util/win32_utils.h
jumanpp-2.0.0-rc2/src/util/hashing.h
jumanpp-2.0.0-rc2/src/util/memory.hpp
jumanpp-2.0.0-rc2/src/util/serialization_flatmap.h
jumanpp-2.0.0-rc2/src/util/csv_reader.h
jumanpp-2.0.0-rc2/src/util/common.hpp
jumanpp-2.0.0-rc2/src/util/mmap.h
jumanpp-2.0.0-rc2/src/util/format.h
jumanpp-2.0.0-rc2/src/util/cfg.h
jumanpp-2.0.0-rc2/src/util/types.hpp
jumanpp-2.0.0-rc2/src/util/mmap_impl_win32.h
jumanpp-2.0.0-rc2/src/util/assert.h
jumanpp-2.0.0-rc2/src/util/array_slice.h
jumanpp-2.0.0-rc2/src/util/array_slice_util.h
jumanpp-2.0.0-rc2/src/util/array_slice_internal.h
jumanpp-2.0.0-rc2/src/util/sliceable_array.h
jumanpp-2.0.0-rc2/src/util/logging.hpp
jumanpp-2.0.0-rc2/src/util/bounded_queue.h
jumanpp-2.0.0-rc2/src/util/characters.h
jumanpp-2.0.0-rc2/src/core/impl/
jumanpp-2.0.0-rc2/src/core/env.h
jumanpp-2.0.0-rc2/src/core/core.h
jumanpp-2.0.0-rc2/src/core/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/features_api.h
jumanpp-2.0.0-rc2/src/core/dic/
jumanpp-2.0.0-rc2/src/core/analysis/
jumanpp-2.0.0-rc2/src/core/core_config.h.in
jumanpp-2.0.0-rc2/src/core/proto/
jumanpp-2.0.0-rc2/src/core/test/
jumanpp-2.0.0-rc2/src/core/core_types.h
jumanpp-2.0.0-rc2/src/core/input/
jumanpp-2.0.0-rc2/src/core/training/
jumanpp-2.0.0-rc2/src/core/spec/
jumanpp-2.0.0-rc2/src/core/core_version.h.in
jumanpp-2.0.0-rc2/src/core/codegen/
jumanpp-2.0.0-rc2/src/core/devtools/
jumanpp-2.0.0-rc2/src/core/benchmarks/
jumanpp-2.0.0-rc2/src/core/core.cc
jumanpp-2.0.0-rc2/src/core/api/
jumanpp-2.0.0-rc2/src/core/features_api.cc
jumanpp-2.0.0-rc2/src/core/env.cc
jumanpp-2.0.0-rc2/src/core/api/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/benchmarks/perceptron_bench_2.cc
jumanpp-2.0.0-rc2/src/core/benchmarks/feature_hash_kernel_bench.cc
jumanpp-2.0.0-rc2/src/core/benchmarks/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/benchmarks/fasthash_bench.cc
jumanpp-2.0.0-rc2/src/core/benchmarks/codegen_bench_01.cc
jumanpp-2.0.0-rc2/src/core/benchmarks/other/
jumanpp-2.0.0-rc2/src/core/benchmarks/perceptron_bench.cc
jumanpp-2.0.0-rc2/src/core/benchmarks/other/spec_01.h
jumanpp-2.0.0-rc2/src/core/devtools/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/devtools/fasthash_quality.cc
jumanpp-2.0.0-rc2/src/core/devtools/strings_alignment_hinter.cc
jumanpp-2.0.0-rc2/src/core/codegen/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/codegen/ngram_feature_codegen.cc
jumanpp-2.0.0-rc2/src/core/codegen/pattern_feature_codegen.h
jumanpp-2.0.0-rc2/src/core/codegen/codegen_main.cc.in
jumanpp-2.0.0-rc2/src/core/codegen/feature_codegen.h
jumanpp-2.0.0-rc2/src/core/codegen/pattern_codegen_test.cc
jumanpp-2.0.0-rc2/src/core/codegen/partial_ngram_feature_codegen.h
jumanpp-2.0.0-rc2/src/core/codegen/ngram_feature_codegen.h
jumanpp-2.0.0-rc2/src/core/codegen/partial_ngram_feature_codegen.cc
jumanpp-2.0.0-rc2/src/core/codegen/pattern_feature_codegen.cc
jumanpp-2.0.0-rc2/src/core/codegen/feature_codegen.cc
jumanpp-2.0.0-rc2/src/core/codegen/cg_2_spec.h
jumanpp-2.0.0-rc2/src/core/codegen/feature_codegen_test.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_dsl.h
jumanpp-2.0.0-rc2/src/core/spec/spec_grammar_test.cc
jumanpp-2.0.0-rc2/src/core/spec/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/spec/spec_dsl_feature_test.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_dsl.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_types.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_types.h
jumanpp-2.0.0-rc2/src/core/spec/spec_compiler.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_compiler.h
jumanpp-2.0.0-rc2/src/core/spec/spec_dsl_test.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_serialization.cc
jumanpp-2.0.0-rc2/src/core/spec/spec_ser.h
jumanpp-2.0.0-rc2/src/core/spec/spec_grammar.h
jumanpp-2.0.0-rc2/src/core/spec/spec_serialization.h
jumanpp-2.0.0-rc2/src/core/training/full_example.h
jumanpp-2.0.0-rc2/src/core/training/trainer.cc
jumanpp-2.0.0-rc2/src/core/training/full_example.cc
jumanpp-2.0.0-rc2/src/core/training/gold_example.cc
jumanpp-2.0.0-rc2/src/core/training/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/training/loss.cc
jumanpp-2.0.0-rc2/src/core/training/trainer_base.cc
jumanpp-2.0.0-rc2/src/core/training/partial_trainer.cc
jumanpp-2.0.0-rc2/src/core/training/scw.h
jumanpp-2.0.0-rc2/src/core/training/training_env.cc
jumanpp-2.0.0-rc2/src/core/training/partial_example_train_test.cc
jumanpp-2.0.0-rc2/src/core/training/training_env.h
jumanpp-2.0.0-rc2/src/core/training/trainer.h
jumanpp-2.0.0-rc2/src/core/training/gold_example2_test.cc
jumanpp-2.0.0-rc2/src/core/training/partial_trainer.h
jumanpp-2.0.0-rc2/src/core/training/training_executor.h
jumanpp-2.0.0-rc2/src/core/training/trainer_base.h
jumanpp-2.0.0-rc2/src/core/training/scw.cc
jumanpp-2.0.0-rc2/src/core/training/training_executor.cc
jumanpp-2.0.0-rc2/src/core/training/gold_example.h
jumanpp-2.0.0-rc2/src/core/training/training_test_common.h
jumanpp-2.0.0-rc2/src/core/training/gold_example_test.cc
jumanpp-2.0.0-rc2/src/core/training/training_types.h
jumanpp-2.0.0-rc2/src/core/training/loss.h
jumanpp-2.0.0-rc2/src/core/training/trainer_test.cc
jumanpp-2.0.0-rc2/src/core/input/training_io.cc
jumanpp-2.0.0-rc2/src/core/input/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/input/partial_example.cc
jumanpp-2.0.0-rc2/src/core/input/stream_reader.h
jumanpp-2.0.0-rc2/src/core/input/partial_example_io.h
jumanpp-2.0.0-rc2/src/core/input/partial_example.h
jumanpp-2.0.0-rc2/src/core/input/training_io.h
jumanpp-2.0.0-rc2/src/core/input/partial_example_io_test.cc
jumanpp-2.0.0-rc2/src/core/input/partial_example_io.cc
jumanpp-2.0.0-rc2/src/core/input/pex_stream_reader.cc
jumanpp-2.0.0-rc2/src/core/input/pex_stream_reader.h
jumanpp-2.0.0-rc2/src/core/input/stream_reader.cc
jumanpp-2.0.0-rc2/src/core/test/test_analyzer_env.h
jumanpp-2.0.0-rc2/src/core/proto/lattice_dump.proto
jumanpp-2.0.0-rc2/src/core/proto/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/proto/lattice_dump_output.cc
jumanpp-2.0.0-rc2/src/core/proto/lattice_dump_output.h
jumanpp-2.0.0-rc2/src/core/analysis/dictionary_node_creator_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/unk_nodes_creator.h
jumanpp-2.0.0-rc2/src/core/analysis/perceptron.h
jumanpp-2.0.0-rc2/src/core/analysis/charlattice_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/rnn_scorer_gbeam.h
jumanpp-2.0.0-rc2/src/core/analysis/onomatopoeia_creator.h
jumanpp-2.0.0-rc2/src/core/analysis/dic_reader.h
jumanpp-2.0.0-rc2/src/core/analysis/output.cc
jumanpp-2.0.0-rc2/src/core/analysis/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/analysis/numeric_creator.h
jumanpp-2.0.0-rc2/src/core/analysis/analysis_input.cc
jumanpp-2.0.0-rc2/src/core/analysis/unk_maker_types.h
jumanpp-2.0.0-rc2/src/core/analysis/analysis_result.h
jumanpp-2.0.0-rc2/src/core/analysis/rnn_scorer_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/unk_nodes.h
jumanpp-2.0.0-rc2/src/core/analysis/analysis_input.h
jumanpp-2.0.0-rc2/src/core/analysis/innode_features.cc
jumanpp-2.0.0-rc2/src/core/analysis/innode_features.h
jumanpp-2.0.0-rc2/src/core/analysis/numeric_creator_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/rnn_scorer.h
jumanpp-2.0.0-rc2/src/core/analysis/score_processor.h
jumanpp-2.0.0-rc2/src/core/analysis/score_plugin.h
jumanpp-2.0.0-rc2/src/core/analysis/lattice_builder_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/rnn_serialization.h
jumanpp-2.0.0-rc2/src/core/analysis/unk_nodes_creator.cc
jumanpp-2.0.0-rc2/src/core/analysis/extra_nodes.h
jumanpp-2.0.0-rc2/src/core/analysis/rnn_id_resolver.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_types.cc
jumanpp-2.0.0-rc2/src/core/analysis/unk_nodes_creator_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/output.h
jumanpp-2.0.0-rc2/src/core/analysis/analyzer.h
jumanpp-2.0.0-rc2/src/core/analysis/normalized_node_creator_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/score_processor_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/analyzer_impl.h
jumanpp-2.0.0-rc2/src/core/analysis/lattice_builder.h
jumanpp-2.0.0-rc2/src/core/analysis/analyzer.cc
jumanpp-2.0.0-rc2/src/core/analysis/dictionary_node_creator.h
jumanpp-2.0.0-rc2/src/core/analysis/charlattice.cc
jumanpp-2.0.0-rc2/src/core/analysis/analyzer_impl_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_types.h
jumanpp-2.0.0-rc2/src/core/analysis/unk_nodes.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_builder.cc
jumanpp-2.0.0-rc2/src/core/analysis/normalized_node_creator.cc
jumanpp-2.0.0-rc2/src/core/analysis/onomatopoeia_creator_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/extra_nodes.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_compactor_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/score_api.h
jumanpp-2.0.0-rc2/src/core/analysis/dictionary_node_creator.cc
jumanpp-2.0.0-rc2/src/core/analysis/charlattice.h
jumanpp-2.0.0-rc2/src/core/analysis/rnn_id_resolver.h
jumanpp-2.0.0-rc2/src/core/analysis/rnn_id_resolver_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/analysis_result.cc
jumanpp-2.0.0-rc2/src/core/analysis/onomatopoeia_creator.cc
jumanpp-2.0.0-rc2/src/core/analysis/numeric_creator.cc
jumanpp-2.0.0-rc2/src/core/analysis/perceptron_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/analyzer_impl.cc
jumanpp-2.0.0-rc2/src/core/analysis/perceptron.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_config.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_types_test.cc
jumanpp-2.0.0-rc2/src/core/analysis/ngram_computations.h
jumanpp-2.0.0-rc2/src/core/analysis/ngram_computations.cc
jumanpp-2.0.0-rc2/src/core/analysis/lattice_config.h
jumanpp-2.0.0-rc2/src/core/analysis/rnn_scorer_gbeam.cc
jumanpp-2.0.0-rc2/src/core/analysis/rnn_scorer.cc
jumanpp-2.0.0-rc2/src/core/analysis/dic_reader.cc
jumanpp-2.0.0-rc2/src/core/analysis/normalized_node_creator.h
jumanpp-2.0.0-rc2/src/core/analysis/score_processor.cc
jumanpp-2.0.0-rc2/src/core/dic/dictionary.cc
jumanpp-2.0.0-rc2/src/core/dic/progress.h
jumanpp-2.0.0-rc2/src/core/dic/dic_feature_impl.h
jumanpp-2.0.0-rc2/src/core/dic/dic_builder.h
jumanpp-2.0.0-rc2/src/core/dic/dic_build_detail.cc
jumanpp-2.0.0-rc2/src/core/dic/field_reader.h
jumanpp-2.0.0-rc2/src/core/dic/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/dic/darts.h
jumanpp-2.0.0-rc2/src/core/dic/dictionary_test.cc
jumanpp-2.0.0-rc2/src/core/dic/darts_trie.h
jumanpp-2.0.0-rc2/src/core/dic/dic_entries.h
jumanpp-2.0.0-rc2/src/core/dic/dic_builder.cc
jumanpp-2.0.0-rc2/src/core/dic/dictionary.h
jumanpp-2.0.0-rc2/src/core/dic/field_import.cc
jumanpp-2.0.0-rc2/src/core/dic/field_reader_test.cc
jumanpp-2.0.0-rc2/src/core/dic/entry_builder.cc
jumanpp-2.0.0-rc2/src/core/dic/darts_trie.cc
jumanpp-2.0.0-rc2/src/core/dic/dic_feature_impl.cc
jumanpp-2.0.0-rc2/src/core/dic/darts_trie_test.cc
jumanpp-2.0.0-rc2/src/core/dic/dic_deduplication_test.cc
jumanpp-2.0.0-rc2/src/core/dic/dic_build_detail.h
jumanpp-2.0.0-rc2/src/core/dic/field_import_test.cc
jumanpp-2.0.0-rc2/src/core/dic/entry_builder.h
jumanpp-2.0.0-rc2/src/core/dic/field_import.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_ngram_partial.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_types.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_prim.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_ngram_partial_test.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_pattern.cc
jumanpp-2.0.0-rc2/src/core/impl/segmented_format.h
jumanpp-2.0.0-rc2/src/core/impl/feature_debug.h
jumanpp-2.0.0-rc2/src/core/impl/CMakeLists.txt
jumanpp-2.0.0-rc2/src/core/impl/global_beam_position_fmt.cc
jumanpp-2.0.0-rc2/src/core/impl/perceptron_io.h
jumanpp-2.0.0-rc2/src/core/impl/global_beam_position_fmt.h
jumanpp-2.0.0-rc2/src/core/impl/model_format.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_ngram_partial_kernels.h
jumanpp-2.0.0-rc2/src/core/impl/model_io.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_combine.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_debug.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_compute_test.cc
jumanpp-2.0.0-rc2/src/core/impl/aligned_field_test.cc
jumanpp-2.0.0-rc2/src/core/impl/kvlist_test.cc
jumanpp-2.0.0-rc2/src/core/impl/segmented_format.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_computer.h
jumanpp-2.0.0-rc2/src/core/impl/graphviz_format.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_combine_test.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_test.cc
jumanpp-2.0.0-rc2/src/core/impl/graphviz_format_test.cc
jumanpp-2.0.0-rc2/src/core/impl/model_io_test.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_ngram_partial.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_compute.cc
jumanpp-2.0.0-rc2/src/core/impl/model_io.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_combine.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_types.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_prim_test.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_compute.h
jumanpp-2.0.0-rc2/src/core/impl/graphviz_format.cc
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_prim.h
jumanpp-2.0.0-rc2/src/core/impl/feature_impl_pattern.h
jumanpp-2.0.0-rc2/src/core/impl/int_seq_util.h
jumanpp-2.0.0-rc2/src/core/impl/feature_computer.cc
jumanpp-2.0.0-rc2/src/core/impl/model_format_ser.h
jumanpp-2.0.0-rc2/src/jumandic/CMakeLists.txt
jumanpp-2.0.0-rc2/src/jumandic/proto/
jumanpp-2.0.0-rc2/src/jumandic/tests/
jumanpp-2.0.0-rc2/src/jumandic/shared/
jumanpp-2.0.0-rc2/src/jumandic/main/
jumanpp-2.0.0-rc2/src/jumandic/main/path_diff.cc
jumanpp-2.0.0-rc2/src/jumandic/main/jumanpp_train.cc
jumanpp-2.0.0-rc2/src/jumandic/main/jumanpp.h
jumanpp-2.0.0-rc2/src/jumandic/main/jumanpp_train.h
jumanpp-2.0.0-rc2/src/jumandic/main/jumanpp.cc
jumanpp-2.0.0-rc2/src/jumandic/main/bootstrap.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumanpp_args.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_id_resolver.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_spec.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_codegen_test.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/lattice_format.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_env.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_test_env.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_ids.h
jumanpp-2.0.0-rc2/src/jumandic/shared/mdic_format_test.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_id_resolver.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/subset_format.h
jumanpp-2.0.0-rc2/src/jumandic/shared/juman_format.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/training_test.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_env.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_spec.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/subset_format.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/lattice_format.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_ids.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jpp_rnn_args.h
jumanpp-2.0.0-rc2/src/jumandic/shared/mdic_format.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_spec_lexdata.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/mini_dic_test.cc
jumanpp-2.0.0-rc2/src/jumandic/shared/morph_format.h
jumanpp-2.0.0-rc2/src/jumandic/shared/mdic_format.h
jumanpp-2.0.0-rc2/src/jumandic/shared/jumandic_spec_test.cc

In [ ]:
# JUMANをPythonで使用するため，pyknpをインストール
!pip install pyknp

Collecting pyknp
  Downloading pyknp-0.6.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 914 kB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from pyknp) (1.15.0)
Installing collected packages: pyknp
Successfully installed pyknp-0.6.1

In [ ]:
# BERTの日本語事前学習済みモデルをダウンロード
import urllib.request
kyoto_u_bert_url = "http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/JapaneseBertPretrainedModel/Japanese_L-12_H-768_A-12_E-30_BPE.zip"
urllib.request.urlretrieve(kyoto_u_bert_url, "Japanese_L-12_H-768_A-12_E-30_BPE.zip")

('Japanese_L-12_H-768_A-12_E-30_BPE.zip',
 <http.client.HTTPMessage at 0x7fb7f6e21250>)

In [ ]:
!unzip Japanese_L-12_H-768_A-12_E-30_BPE.zip # 解凍する

Archive:  Japanese_L-12_H-768_A-12_E-30_BPE.zip
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/README.txt
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/bert_config.json
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/bert_model.ckpt.data-00000-of-00001
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/bert_model.ckpt.index
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/bert_model.ckpt.meta
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/pytorch_model.bin
  inflating: Japanese_L-12_H-768_A-12_E-30_BPE/vocab.txt

In [ ]:
# # BERTの公式リポジトリをクローン（これは実行してはならない！！！書いたのが変更されてしまう．）
# !git clone https://github.com/google-research/bert.git

In [ ]:
# デフォルトではtensorflowは2系なので1系に変更
%tensorflow_version 1.x

TensorFlow 1.x selected.

In [ ]:
!mkdir /content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT

mkdir: cannot create directory ‘/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo’: File exists
mkdir: cannot create directory ‘accountに保存）/Suspection/model_BERT’: No such file or directory

In [ ]:
cd /content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT

/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT

In [ ]:
import pandas as pd
import sys
import os
import glob
import unicodedata
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 訓練データを公式のデータである34話以降，テストデータを非公式のデータである33話までのデータとする

classes = [0,1]

if __name__ == '__main__':
    df_series = pd.read_csv("/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/dataset/nishimura_data.csv")
    df_series["Empty_Col"] = ""
    df_all = df_series

    df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace('、', ',')
    df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace('。', '.')
    # df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace('\u3000', '')
    df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace('\n', '')
    df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace('　', '')
    df_all["synopsis_plus_cast_info"] = df_all["synopsis_plus_cast_info"].str.replace(' ', '')

    df_test = df_all[df_all.id > 67][["criminal", "Empty_Col", "synopsis_plus_cast_info"]] # 16話まで
    df_all_new = df_all[df_all.id < 68][["criminal", "Empty_Col", "synopsis_plus_cast_info"]]
    x_train, x_valid, Y_train, Y_valid = train_test_split(df_all_new.synopsis_plus_cast_info, df_all_new.criminal, test_size=0.2, random_state=42)

    df_train = pd.concat([x_train, Y_train], axis=1)
    df_validation = pd.concat([x_valid, Y_valid], axis=1)

    # df_train = df_all[df_all.id > 19][["criminal", "Empty_Col", "synopsis_plus_cast_info"]] # 34話以降
    # df_validation = df_all[(df_all.id > 9) & (df_all.id < 20)][["criminal", "Empty_Col", "synopsis_plus_cast_info"]] # 17話から33話まで
    
    df_all = df_all[["criminal", "Empty_Col", "synopsis_plus_cast_info"]]


    

    # tsvで出力する
    df_all.to_csv('/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/all.tsv', sep='\t')
    df_train.to_csv('/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/train.tsv', sep='\t')
    df_validation.to_csv('/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/dev.tsv', sep='\t')
    df_test.to_csv('/content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/test.tsv', sep='\t')


print(len(df_all))
print(len(df_train))
print(len(df_validation))
print(len(df_test))

df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace('、', ',')
df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace('。', '.')
df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace('\u3000', '')
df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace('\n', '')
df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace('　', '')
df_train["synopsis_plus_cast_info"] = df_train["synopsis_plus_cast_info"].str.replace(' ', '')


df_test.head()

678
495
92
91

   criminal Empty_Col                            synopsis_plus_cast_info
0         0            青森県立F高校の卒業生で校内新聞の編集長だった宮本孝は,卒業する時に交わした「7年経ったら皆...
1         0            青森県立F高校の卒業生で校内新聞の編集長だった宮本孝は,卒業する時に交わした「7年経ったら皆...
2         0            青森県立F高校の卒業生で校内新聞の編集長だった宮本孝は,卒業する時に交わした「7年経ったら皆...
3         0            青森県立F高校の卒業生で校内新聞の編集長だった宮本孝は,卒業する時に交わした「7年経ったら皆...
4         0            青森県立F高校の卒業生で校内新聞の編集長だった宮本孝は,卒業する時に交わした「7年経ったら皆...

In [ ]:
# データをBERTで扱いやすいようなフォーマットに変更する

import tarfile
import csv
import re

target_genre = ["0", "1"]

zero_fnames = []
one_fnames = []

train_fname, dev_fname, test_fname = ["train.tsv", "dev.tsv", "test.tsv"]


brackets_tail = re.compile('【[^】]*】$')
brackets_head = re.compile('^【[^】]*】')

def remove_brackets(inp):
    output = re.sub(brackets_head, '',re.sub(brackets_tail, '', inp))

    # 全角スペースを除去
    output = output.replace("　", " ")
    return output

def read_title(f):
    next(f)
    next(f)
    title = next(f)
    title = remove_brackets(title.decode('utf-8'))
    return title[:-1]

# with tarfile.open("ldcc-20140209.tar.gz") as tf:
#     with open(train_fname, "w") as wf:
#         writer = csv.writer(wf, delimiter='\t')
#         for name in zero_fnames:
#             f = tf.extractfile(name)
#             title = read_title(f)
#             row = [target_genre[0], 0, '', title]
#             writer.writerow(row)
#         for name in one_fnames:
#             f = tf.extractfile(name)
#             title = read_title(f)
#             row = [target_genre[1], 1, '', title]
#             writer.writerow(row)

In [ ]:
# all.tsvを学習用とテスト用に分割
import random

random.seed(100)
# with open("all.tsv", 'r') as f, open("rand-all.tsv", "w") as wf:
#     lines = f.readlines()
#     random.shuffle(lines)
#     for line in lines:
#         wf.write(line)

random.seed(101)

# with open("rand-all.tsv") as f, open(train_fname, "w") as tf, open(dev_fname, "w") as df, open(test_fname, "w") as ef:
#     ef.write("class\tsentence\n")
#     for line in f:
#         v = random.randint(0, 9)
#         if v == 8:
#             df.write(line)
#         elif v == 9:
#             ef.write(line)
#         else:
#             tf.write(line)

In [ ]:
df_train.head()

     criminal Empty_Col                            synopsis_plus_cast_info
183         1            東都大学民芸品研究会の親睦同窓会に出席してサトコやサトコの友人（城所磨里）,幸子（岡まゆみ）...
184         1            東都大学民芸品研究会の親睦同窓会に出席してサトコやサトコの友人（城所磨里）,幸子（岡まゆみ）...
185         0            東都大学民芸品研究会の親睦同窓会に出席してサトコやサトコの友人（城所磨里）,幸子（岡まゆみ）...
186         0            東都大学民芸品研究会の親睦同窓会に出席してサトコやサトコの友人（城所磨里）,幸子（岡まゆみ）...
187         0            東都大学民芸品研究会の親睦同窓会に出席してサトコやサトコの友人（城所磨里）,幸子（岡まゆみ）...

In [ ]:
# Fine-tuningを行う
!python bert/run_classifier_suspection.py \
--task_name=suspection \
--do_train=true \
--do_eval=true \
--data_dir=./ \
--vocab_file=./Japanese_L-12_H-768_A-12_E-30_BPE/vocab.txt \
--bert_config_file=./Japanese_L-12_H-768_A-12_E-30_BPE/bert_config.json \
--init_checkpoint=./Japanese_L-12_H-768_A-12_E-30_BPE/bert_model.ckpt \
--max_seq_length=512 \
--train_batch_size=32 \
--learning_rate=2e-5 \
--num_train_epochs=3.0 \
--output_dir=./tmp/suspection_output_fine \
--do_lower_case False

WARNING:tensorflow:From /content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:1033: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:835: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0107 07:19:34.096266 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:835: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:835: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0107 07:19:34.096513 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:835: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From /content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/modeling.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0107 07:19:34.097208 140432194742144 module_wrapper.py:139] From /content/drive/MyDrive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/modeling.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:860: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0107 07:19:34.266506 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:860: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0107 07:19:34.802408 140432194742144 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

I0107 07:19:35.724933 140432194742144 utils.py:157] NumExpr defaulting to 2 threads.
WARNING:tensorflow:From bert/run_classifier_suspection.py:206: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

W0107 07:19:36.489104 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:206: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb87a84a0e0>) includes params argument, but params are not passed to Estimator.
W0107 07:19:36.510149 140432194742144 estimator.py:1994] Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb87a84a0e0>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_model_dir': './tmp/suspection_output_fine', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb87a7af550>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
I0107 07:19:36.511121 140432194742144 estimator.py:212] Using config: {'_model_dir': './tmp/suspection_output_fine', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb87a7af550>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
I0107 07:19:36.511436 140432194742144 tpu_context.py:220] _TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
W0107 07:19:36.511693 140432194742144 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:From bert/run_classifier_suspection.py:534: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

W0107 07:19:36.511983 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:534: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:538: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0107 07:19:37.255034 140432194742144 module_wrapper.py:139] From bert/run_classifier_suspection.py:538: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Writing example 0 of 495
I0107 07:19:37.255351 140432194742144 run_classifier_suspection.py:538] Writing example 0 of 495
['東', '都', '大学', '民芸', '品', '研究', '会', 'の', '親睦', '同窓', '会', 'に', '出席', 'して', 'サトコ', 'や', 'サトコ', 'の', '友人', '（', '城所', '磨里', '）', ',', '幸子', '（', '岡', 'まゆみ', '）', ',', '遠山', '（', '山本', '亘', '）', 'と', '再会', 'した', '警視', '庁', '捜査', '一', '課', 'の', '西本', '刑事', '（', '森本', 'レオ', '）', 'は', ',', '十津川', '警部', '（', '三', '橋達也', '）', 'から', '休暇', 'を', '貰って', '遠山', 'と', '一緒に', '長野', 'へ', '旅行', 'に', '出掛ける', '.', '会社', 'を', '辞めて', ',', '長年', 'の', '夢', 'だった', '作家', 'に', 'なる', 'つもりだ', 'と', '話す', '遠山', 'が', '上諏訪', 'で', '降りた', '後', ',', '西本', 'の', '乗った', '列車', 'で', '東京', 'に', '住む', '和田', '晴記', '（', '青柳', '三十六', '）', 'が', '殺さ', 'れ', ',', '捜査', '一', '課', 'の', '清水', '新一', '（', '井川', '晃一', '）', 'と', '北条', '早苗', '（', '山村', '紅葉', '）', 'は', ',', '和田', 'の', '隣室', 'に', '住む', '男性', '（', '田口', '主将', '）', 'や', '和田', 'の', '勤務', '先', 'の', '大木', '運送', 'の', '社員', '（', '清水', '照夫', '）', 'を', '訪ねる', '.', '和田', 'は', 'カメラ', 'が', '趣味', 'だった', 'が', ',', '和田', 'と', '関係', 'の', 'あった', 'かおる', '（', '斉藤', '絵里', '）', 'の', '証言', 'に', 'よって', ',', '和田', 'が', '持って', 'いた', 'と', '思わ', 'れる', 'ライカ', 'が', 'バッグ', 'ごと', '無くなって', 'いる', 'こと', 'が', '判明', 'する', '.', '西本', 'と', '一緒に', '毎朝', '新聞', 'の', '社員', '（', '石波', '義人', '）', 'に', '会った', '亀井', '定夫', '（', '愛川', '欽也', '）', 'は', ',', '和田', 'が', '写真', 'を', 'ネタ', 'に', '誰', 'か', 'を', '強請', 'って', 'いた', 'ので', 'は', 'ない', 'か', 'と', '考える', '.', '探偵', 'の', '浜野', '健一', 'が', '殺さ', 'れ', ',', '和田', 'が', '放火', 'で', '焼死', 'した', '今日子', '（', '清水', 'ひとみ', '）', 'の', '調査', 'を', '浜野', 'に', '依頼', 'して', 'いた', 'こと', 'が', '分かる', '.', '今日子', 'は', '産業', '省', 'の', 'エリート', '官僚', 'の', '崎田', '（', '長谷川', '哲夫', '）', 'と', '不倫', '関係', 'に', 'あった', 'が', ',', '今日子', 'が', '焼死', 'した', '日', ',', '崎田', 'は', '妻', 'の', '幸子', 'や', '息子', 'の', '浩介', '（', '土倉', '有貴', '）', 'を', '連れて', '箱根', 'に', '出掛けて', 'いた', '.', '犯人', 'は', ',', '幸子', '!', '!', '!']
INFO:tensorflow:*** Example ***
I0107 07:19:37.294143 140432194742144 run_classifier_suspection.py:512] *** Example ***
INFO:tensorflow:guid: train-1
I0107 07:19:37.294487 140432194742144 run_classifier_suspection.py:513] guid: train-1
INFO:tensorflow:tokens: [CLS] 東 都 大学 民 ##芸 品 研究 会 の [UNK] 同窓 会 に 出席 して サト ##コ や サト ##コ の 友人 （ 城 ##所 磨 ##里 ） [UNK] 幸子 （ 岡 ま ##ゆみ ） [UNK] 遠山 （ 山本 亘 ） と 再会 した 警視 庁 捜査 一 課 の 西本 刑事 （ 森本 レオ ） は [UNK] 十津川 警部 （ 三 橋 ##達 ##也 ） から 休暇 を 貰 ##って 遠山 と 一緒に 長野 へ 旅行 に 出 ##掛け ##る [UNK] 会社 を 辞めて [UNK] 長年 の 夢 だった 作家 に なる つもり ##だ と 話す 遠山 が [UNK] で 降りた 後 [UNK] 西本 の 乗った 列車 で 東京 に 住む 和田 晴 ##記 （ 青 ##柳 三十 ##六 ） が 殺さ れ [UNK] 捜査 一 課 の 清水 新一 （ 井川 晃 ##一 ） と 北条 早 ##苗 （ 山村 紅葉 ） は [UNK] 和田 の 隣 ##室 に 住む 男性 （ 田口 主将 ） や 和田 の 勤務 先 の 大木 運送 の 社員 （ 清水 照 ##夫 ） を 訪ねる [UNK] 和田 は カメラ が 趣味 だった が [UNK] 和田 と 関係 の あった か ##お ##る （ 斉藤 絵 ##里 ） の 証言 に よって [UNK] 和田 が 持って いた と 思わ れる ライカ が バッグ ごと 無くなって いる こと が 判明 する [UNK] 西本 と 一緒に 毎 ##朝 新聞 の 社員 （ 石 ##波 義 ##人 ） に 会った 亀井 定 ##夫 （ 愛 ##川 欽 ##也 ） は [UNK] 和田 が 写真 を ネタ に 誰 か を 強 ##請 って いた ので は ない か と 考える [UNK] 探偵 の 浜 ##野 健一 が 殺さ れ [UNK] 和田 が 放火 で 焼 ##死 した 今日 ##子 （ 清水 ひとみ ） の 調査 を 浜 ##野 に 依頼 して いた こと が 分かる [UNK] 今日 ##子 は 産業 省 の エリート 官僚 の 崎 ##田 （ 長谷川 哲 ##夫 ） と 不倫 関係 に あった が [UNK] 今日 ##子 が 焼 ##死 した 日 [UNK] 崎 ##田 は 妻 の 幸子 や 息子 の 浩 ##介 （ 土 ##倉 有 ##貴 ） を 連れて 箱根 に 出 ##掛けて いた [UNK] 犯人 は [UNK] 幸子 [UNK] [UNK] [UNK] [SEP]
I0107 07:19:37.294848 140432194742144 run_classifier_suspection.py:515] tokens: [CLS] 東 都 大学 民 ##芸 品 研究 会 の [UNK] 同窓 会 に 出席 して サト ##コ や サト ##コ の 友人 （ 城 ##所 磨 ##里 ） [UNK] 幸子 （ 岡 ま ##ゆみ ） [UNK] 遠山 （ 山本 亘 ） と 再会 した 警視 庁 捜査 一 課 の 西本 刑事 （ 森本 レオ ） は [UNK] 十津川 警部 （ 三 橋 ##達 ##也 ） から 休暇 を 貰 ##って 遠山 と 一緒に 長野 へ 旅行 に 出 ##掛け ##る [UNK] 会社 を 辞めて [UNK] 長年 の 夢 だった 作家 に なる つもり ##だ と 話す 遠山 が [UNK] で 降りた 後 [UNK] 西本 の 乗った 列車 で 東京 に 住む 和田 晴 ##記 （ 青 ##柳 三十 ##六 ） が 殺さ れ [UNK] 捜査 一 課 の 清水 新一 （ 井川 晃 ##一 ） と 北条 早 ##苗 （ 山村 紅葉 ） は [UNK] 和田 の 隣 ##室 に 住む 男性 （ 田口 主将 ） や 和田 の 勤務 先 の 大木 運送 の 社員 （ 清水 照 ##夫 ） を 訪ねる [UNK] 和田 は カメラ が 趣味 だった が [UNK] 和田 と 関係 の あった か ##お ##る （ 斉藤 絵 ##里 ） の 証言 に よって [UNK] 和田 が 持って いた と 思わ れる ライカ が バッグ ごと 無くなって いる こと が 判明 する [UNK] 西本 と 一緒に 毎 ##朝 新聞 の 社員 （ 石 ##波 義 ##人 ） に 会った 亀井 定 ##夫 （ 愛 ##川 欽 ##也 ） は [UNK] 和田 が 写真 を ネタ に 誰 か を 強 ##請 って いた ので は ない か と 考える [UNK] 探偵 の 浜 ##野 健一 が 殺さ れ [UNK] 和田 が 放火 で 焼 ##死 した 今日 ##子 （ 清水 ひとみ ） の 調査 を 浜 ##野 に 依頼 して いた こと が 分かる [UNK] 今日 ##子 は 産業 省 の エリート 官僚 の 崎 ##田 （ 長谷川 哲 ##夫 ） と 不倫 関係 に あった が [UNK] 今日 ##子 が 焼 ##死 した 日 [UNK] 崎 ##田 は 妻 の 幸子 や 息子 の 浩 ##介 （ 土 ##倉 有 ##貴 ） を 連れて 箱根 に 出 ##掛けて いた [UNK] 犯人 は [UNK] 幸子 [UNK] [UNK] [UNK] [SEP]
INFO:tensorflow:input_ids: 2 181 406 82 1556 8028 695 160 126 5 1 16737 126 8 4583 19 31060 517 34 31060 517 5 2502 16 413 2463 14131 1979 17 1 28746 16 5795 1593 31832 17 1 19189 16 3423 14327 17 12 7898 20 6811 1040 3234 70 3862 5 30511 3587 16 25017 6600 17 9 1 30978 15804 16 168 783 6442 3446 17 27 11655 10 13493 617 19189 12 3353 2042 61 2362 8 1047 17786 668 1 184 10 26032 1 4058 5 2104 137 1245 8 66 8954 1201 12 7309 19189 11 1 13 29867 62 1 30511 5 12473 515 13 133 8 3404 7661 4784 3805 16 1531 7791 13336 4291 17 11 4797 54 1 3234 70 3862 5 4093 30984 16 26308 13466 794 17 12 4411 2852 17499 16 16466 16294 17 9 1 7661 5 3893 2999 8 3404 1032 16 18881 9908 17 34 7661 5 2151 678 5 16374 10386 5 4461 16 4093 5486 1792 17 10 30690 1 7661 9 2771 11 3522 137 11 1 7661 12 250 5 139 90 2920 668 16 13790 1868 1979 17 5 4657 8 86 1 7661 11 822 37 12 1578 41 30337 11 15172 1298 26471 21 30 11 3184 22 1 30511 12 3353 4017 3607 980 5 4461 16 497 2333 1010 801 17 8 16845 20433 2265 1792 16 1096 521 15465 3446 17 9 1 7661 11 1053 10 4665 8 2437 90 10 1601 15869 7003 37 314 9 47 90 12 2733 1 5847 5 3544 644 16293 11 4797 54 1 7661 11 14293 13 5471 4844 20 2281 281 16 4093 24708 17 5 425 10 3544 644 8 2630 19 37 30 11 8554 1 2281 281 9 929 335 5 12992 4970 5 18352 470 16 9086 9560 1792 17 12 23076 250 8 139 11 1 2281 281 11 5471 4844 20 29 1 18352 470 9 875 5 28746 34 1072 5 6400 3020 16 1516 3395 1491 6161 17 10 4791 9189 8 1047 27794 37 1 5668 9 1 28746 1 1 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
I0107 07:19:37.295243 140432194742144 run_classifier_suspection.py:516] input_ids: 2 181 406 82 1556 8028 695 160 126 5 1 16737 126 8 4583 19 31060 517 34 31060 517 5 2502 16 413 2463 14131 1979 17 1 28746 16 5795 1593 31832 17 1 19189 16 3423 14327 17 12 7898 20 6811 1040 3234 70 3862 5 30511 3587 16 25017 6600 17 9 1 30978 15804 16 168 783 6442 3446 17 27 11655 10 13493 617 19189 12 3353 2042 61 2362 8 1047 17786 668 1 184 10 26032 1 4058 5 2104 137 1245 8 66 8954 1201 12 7309 19189 11 1 13 29867 62 1 30511 5 12473 515 13 133 8 3404 7661 4784 3805 16 1531 7791 13336 4291 17 11 4797 54 1 3234 70 3862 5 4093 30984 16 26308 13466 794 17 12 4411 2852 17499 16 16466 16294 17 9 1 7661 5 3893 2999 8 3404 1032 16 18881 9908 17 34 7661 5 2151 678 5 16374 10386 5 4461 16 4093 5486 1792 17 10 30690 1 7661 9 2771 11 3522 137 11 1 7661 12 250 5 139 90 2920 668 16 13790 1868 1979 17 5 4657 8 86 1 7661 11 822 37 12 1578 41 30337 11 15172 1298 26471 21 30 11 3184 22 1 30511 12 3353 4017 3607 980 5 4461 16 497 2333 1010 801 17 8 16845 20433 2265 1792 16 1096 521 15465 3446 17 9 1 7661 11 1053 10 4665 8 2437 90 10 1601 15869 7003 37 314 9 47 90 12 2733 1 5847 5 3544 644 16293 11 4797 54 1 7661 11 14293 13 5471 4844 20 2281 281 16 4093 24708 17 5 425 10 3544 644 8 2630 19 37 30 11 8554 1 2281 281 9 929 335 5 12992 4970 5 18352 470 16 9086 9560 1792 17 12 23076 250 8 139 11 1 2281 281 11 5471 4844 20 29 1 18352 470 9 875 5 28746 34 1072 5 6400 3020 16 1516 3395 1491 6161 17 10 4791 9189 8 1047 27794 37 1 5668 9 1 28746 1 1 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
I0107 07:19:37.295542 140432194742144 run_classifier_suspection.py:517] input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
I0107 07:19:37.295781 140432194742144 run_classifier_suspection.py:518] segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
INFO:tensorflow:label: 1 (id = 1)
I0107 07:19:37.390754 140432194742144 run_classifier_suspection.py:519] label: 1 (id = 1)

In [ ]:
# fine-tuningを行ったモデルを使ってtest.tsvを二値分類し，結果を出力
!python bert/run_classifier_suspection.py \
  --task_name=suspection \
  --do_predict=true \
  --data_dir=./ \
  --vocab_file=./Japanese_L-12_H-768_A-12_E-30_BPE/vocab.txt \
  --bert_config_file=./Japanese_L-12_H-768_A-12_E-30_BPE/bert_config.json \
  --init_checkpoint=./tmp/suspection_output_fine \
  --max_seq_length=512 \
  --output_dir=tmp/suspection_output_predic/

WARNING:tensorflow:From /content/drive/My Drive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/optimization.py:87: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:1033: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:835: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0107 07:20:38.702340 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:835: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:835: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0107 07:20:38.702583 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:835: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From /content/drive/My Drive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/modeling.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0107 07:20:38.703100 140128358901632 module_wrapper.py:139] From /content/drive/My Drive/PAI_PROJECT_analysis（全体の内容はU-tokyo google accountに保存）/Suspection/model_BERT/bert/modeling.py:93: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:860: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0107 07:20:38.705267 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:860: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0107 07:20:38.846788 140128358901632 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

I0107 07:20:39.445259 140128358901632 utils.py:157] NumExpr defaulting to 2 threads.
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f71bc7d90e0>) includes params argument, but params are not passed to Estimator.
W0107 07:20:39.799853 140128358901632 estimator.py:1994] Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f71bc7d90e0>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Using config: {'_model_dir': 'tmp/suspection_output_predic/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f71bc798b50>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
I0107 07:20:39.800818 140128358901632 estimator.py:212] Using config: {'_model_dir': 'tmp/suspection_output_predic/', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f71bc798b50>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
I0107 07:20:39.801133 140128358901632 tpu_context.py:220] _TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
W0107 07:20:39.801356 140128358901632 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
WARNING:tensorflow:From bert/run_classifier_suspection.py:206: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

W0107 07:20:39.801689 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:206: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:534: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

W0107 07:20:39.807219 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:534: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

WARNING:tensorflow:From bert/run_classifier_suspection.py:538: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0107 07:20:40.311052 140128358901632 module_wrapper.py:139] From bert/run_classifier_suspection.py:538: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Writing example 0 of 91
I0107 07:20:40.311555 140128358901632 run_classifier_suspection.py:538] Writing example 0 of 91
['青森', '県立', 'F', '高校', 'の', '卒業', '生', 'で', '校', '内', '新聞', 'の', '編集', '長', 'だった', '宮本', '孝', 'は', ',', '卒業', 'する', '時', 'に', '交わした', '「', '7', '年', '経ったら', '皆', 'で', '青森', 'に', '帰郷', 'しよう', '」', 'と', 'いう', '約束', 'に', '従い', ',', '2', '泊', '3', '日', 'の', '帰郷', '旅行', 'の', '計画', 'を', '立てて', '他', 'の', 'メンバー', '6', '人', 'に', '寝台', '特急', 'ゆう', 'づる', '7', '号', 'の', '切符', 'と', '手紙', 'を', '送った', '.', 'そして', '出発', '当日', 'の', '4', '月', '1', '日', ',', '上野', '駅', 'に', 'は', '宮本', 'を', '入れた', '6', '人', '（', '片岡', '清之', ',', '川島', '史郎', ',', '村上', '陽子', ',', '橋口', 'まゆみ', ',', '町田', '隆夫', '）', 'が', '顔', 'を', '揃えた', 'が', ',', '残る', '1', '人', '・', '安田', '章', 'は', 'ゆう', 'づる', '7', '号', 'の', '発車', '時間', 'に', 'なって', 'も', '上野', '駅', 'に', 'は', '現れ', 'なかった', '.', 'ゆう', 'づる', '7', '号', 'は', ',', '1', '人', '足り', 'ない', '6', '人', 'を', '乗せて', '上野', '駅', 'を', '出発', 'した', '.', '一方', ',', '警視', '庁', '捜査', '一', '課', 'の', '亀井', '刑事', 'は', ',', '青森', 'から', '上京', 'した', '旧友', '・', '森下', 'から', '「', '自分', 'の', '教え子', 'である', '松木', '紀子', 'と', 'いう', '女性', 'が', '最近', '2', '年間', '消息', '不明な', 'ので', '一緒に', '彼女', 'を', '探して', 'ほしい', '」', 'と', '頼ま', 'れる', '.', 'その', '帰り道', ',', '亀井', '刑事', 'は', '上野', '駅', 'の', 'トイレ', 'の', '中', 'で', '刺殺', '体', 'が', '発見', 'さ', 'れる', '事件', 'に', '遭遇', ',', 'その', '死体', 'の', '主', 'は', '待ち合わせ', 'の', '場所', 'に', '来', 'なかった', '安田', '章', 'だった', '.', '列車', 'が', '仙台', 'を', '過ぎた', '頃', ',', '町田', 'が', '「', '川島', 'の', '姿', 'が', '見え', 'ない', '」', 'と', '宮本', 'を', '叩き起こす', '.', '確かに', '寝台', 'の', '中', 'に', '川島', 'は', 'い', 'なかった', '.', 'だが', ',', '川島', 'が', '見つかる', 'こと', 'も', 'なく', ',', '列車', 'は', '青森', '駅', 'に', '到着', 'する', '.', '青森', '県警', 'の', '三浦', '刑事', 'が', '出迎え', ',', '5', '人', 'は', '安田', 'が', '殺さ', 'れた', 'こと', 'を', '知ら', 'さ', 'れる', '.', '当初', ',', '川島', 'が', '安田', 'を', '殺害', 'して', '逃亡', 'した', 'ので', 'は', 'と', '思わ', 'れた', 'が', ',', '川島', 'は', 'その後', ',', '鬼怒川', 'で', '水死', '体', 'で', '発見', 'さ', 'れ', ',', '自殺', 'と', '思わ', 'れた', '.', '宮本', 'ら', '5', '人', 'は', '青森', '県警', '本部', 'で', 'の', '事情', '聴取', 'の', '後', ',', '三浦', '刑事', 'から', '青森', '市', '内', 'の', 'ホテル', 'に', '足止め', 'を', '喰らう', 'が', ',', 'ホテル', 'の', '部屋', 'で', '橋口', 'まゆみ', 'が', '遺書', 'を', '残して', '死亡', 'する', '.', '自殺', 'か', 'と', 'も', '思わ', 'れた', 'が', '他殺', 'の', '疑い', 'も', '濃厚であり', ',', '青森', '県警', 'の', '捜査', 'も', '混迷', 'を', '極める', '.', '結局', ',', '決定', '的な', '証拠', 'が', '見つから', 'ない', 'まま', '県警', 'の', '捜査', '本部', 'は', '解散', 'する', 'が', ',', '今度', 'は', '青森', '駅', 'の', '待合室', 'で', '村上', '陽子', 'が', '他殺', '体', 'で', '発見', 'さ', 'れる', '.', '同じ', '頃', ',', '東京', 'でも', '上野', '署', 'の', '捜査', '本部', 'が', '解散', 'さ', 'れよう', 'と', 'して', 'いた', 'が', ',', '上野', '駅', 'で', '片岡', '清之', 'が', '毒殺', 'さ', 'れた', 'と', 'の', '連絡', 'が', '入る', '.', '最終', '的に', '旧友', '7', '人', 'は', ',', '生存', '者', 'が', '宮本', 'と', '町田', 'の', '2', '人', 'に', 'なって', 'しまう', '.', '当然', ',', 'どちら', 'か', 'が', '犯人', 'と', '十津川', '警部', 'ら', '捜査', '一', '課', 'の', '刑事', 'は', '結論', 'を', '出す', 'が', ',', 'いずれ', 'か', '1', '人', 'で', 'は', '全員', 'を', '殺害', 'する', 'こと', 'が', '物理', '的に', '不可能', 'と', '判明', 'する', '.', '最後の', '1', '人', 'が', '殺さ', 'れた', '時', ',', '意外な', '犯人', 'の', '顔', 'が', '浮かび', '上がった', '.', '動機', 'は', '何', 'な', 'の', 'か', '？', '十津川', 'が', '7', '年', '前', 'の', '悲痛な', '事件', 'を', '暴き', '出した', '時', ',', 'すべて', 'が', '明らかに', 'なった', '！', '犯人', 'は', ',', '亀井', '刑事', '!', '!', '!']
INFO:tensorflow:*** Example ***
I0107 07:20:40.402982 140128358901632 run_classifier_suspection.py:512] *** Example ***
INFO:tensorflow:guid: test-1
I0107 07:20:40.403350 140128358901632 run_classifier_suspection.py:513] guid: test-1
INFO:tensorflow:tokens: [CLS] 青森 県立 [UNK] 高校 の 卒業 生 で 校 内 新聞 の 編集 長 だった 宮本 孝 は [UNK] 卒業 する 時 に 交わした 「 [UNK] 年 経った ##ら 皆 で 青森 に 帰郷 しよう 」 と いう 約束 に 従い [UNK] [UNK] 泊 [UNK] 日 の 帰郷 旅行 の 計画 を 立てて 他 の メンバー [UNK] 人 に 寝台 特急 ゆう づ ##る [UNK] 号 の 切符 と 手紙 を 送った [UNK] そして 出発 当日 の [UNK] 月 [UNK] 日 [UNK] 上野 駅 に は 宮本 を 入れた [UNK] 人 （ 片岡 清 ##之 [UNK] 川島 史 ##郎 [UNK] 村上 陽子 [UNK] 橋 ##口 ま ##ゆみ [UNK] 町田 隆 ##夫 ） が 顔 を 揃え ##た が [UNK] 残る [UNK] 人 ・ 安田 章 は ゆう づ ##る [UNK] 号 の 発車 時間 に なって も 上野 駅 に は 現れ なかった [UNK] ゆう づ ##る [UNK] 号 は [UNK] [UNK] 人 足り ない [UNK] 人 を 乗せて 上野 駅 を 出発 した [UNK] 一方 [UNK] 警視 庁 捜査 一 課 の 亀井 刑事 は [UNK] 青森 から 上京 した 旧友 ・ 森下 から 「 自分 の 教え子 である 松 ##木 紀 ##子 と いう 女性 が 最近 [UNK] 年間 消息 不明な ので 一緒に 彼女 を 探して ほしい 」 と 頼ま れる [UNK] その 帰り ##道 [UNK] 亀井 刑事 は 上野 駅 の トイレ の 中 で 刺殺 体 が 発見 さ れる 事件 に 遭遇 [UNK] その 死体 の 主 は 待ち ##合わせ の 場所 に 来 なかった 安田 章 だった [UNK] 列車 が 仙台 を 過ぎた 頃 [UNK] 町田 が 「 川島 の 姿 が 見え ない 」 と 宮本 を 叩き ##起こす [UNK] 確かに 寝台 の 中 に 川島 は い なかった [UNK] だが [UNK] 川島 が 見つかる こと も なく [UNK] 列車 は 青森 駅 に 到着 する [UNK] 青森 県警 の 三浦 刑事 が [UNK] [UNK] [UNK] 人 は 安田 が 殺さ れた こと を 知ら さ れる [UNK] 当初 [UNK] 川島 が 安田 を 殺害 して 逃亡 した ので は と 思わ れた が [UNK] 川島 は その後 [UNK] 鬼 ##怒 ##川 で 水 ##死 体 で 発見 さ れ [UNK] 自殺 と 思わ れた [UNK] 宮本 ら [UNK] 人 は 青森 県警 本部 で の 事情 聴取 の 後 [UNK] 三浦 刑事 から 青森 市 内 の ホテル に 足 ##止め を 喰 ##らう が [UNK] ホテル の 部屋 で 橋 ##口 ま ##ゆみ が 遺書 を 残して 死亡 する [UNK] 自殺 か と も 思わ れた が 他 ##殺 の 疑い も 濃 ##厚 ##であり [UNK] 青森 県警 の 捜査 も 混 ##迷 を 極め ##る [UNK] 結局 [UNK] 決定 的な 証拠 が 見つから ない まま 県警 の 捜査 本部 は 解散 する が [UNK] 今度 は 青森 駅 の 待合室 で 村上 陽子 が 他 ##殺 体 で 発見 さ れる [UNK] 同じ 頃 [UNK] 東京 でも 上野 署 の 捜査 本部 が 解散 さ れよう と して いた が [UNK] 上野 駅 で 片岡 清 ##之 が 毒殺 さ れた と の 連絡 が 入る [UNK] 最終 的に 旧友 [SEP]
I0107 07:20:40.403727 140128358901632 run_classifier_suspection.py:515] tokens: [CLS] 青森 県立 [UNK] 高校 の 卒業 生 で 校 内 新聞 の 編集 長 だった 宮本 孝 は [UNK] 卒業 する 時 に 交わした 「 [UNK] 年 経った ##ら 皆 で 青森 に 帰郷 しよう 」 と いう 約束 に 従い [UNK] [UNK] 泊 [UNK] 日 の 帰郷 旅行 の 計画 を 立てて 他 の メンバー [UNK] 人 に 寝台 特急 ゆう づ ##る [UNK] 号 の 切符 と 手紙 を 送った [UNK] そして 出発 当日 の [UNK] 月 [UNK] 日 [UNK] 上野 駅 に は 宮本 を 入れた [UNK] 人 （ 片岡 清 ##之 [UNK] 川島 史 ##郎 [UNK] 村上 陽子 [UNK] 橋 ##口 ま ##ゆみ [UNK] 町田 隆 ##夫 ） が 顔 を 揃え ##た が [UNK] 残る [UNK] 人 ・ 安田 章 は ゆう づ ##る [UNK] 号 の 発車 時間 に なって も 上野 駅 に は 現れ なかった [UNK] ゆう づ ##る [UNK] 号 は [UNK] [UNK] 人 足り ない [UNK] 人 を 乗せて 上野 駅 を 出発 した [UNK] 一方 [UNK] 警視 庁 捜査 一 課 の 亀井 刑事 は [UNK] 青森 から 上京 した 旧友 ・ 森下 から 「 自分 の 教え子 である 松 ##木 紀 ##子 と いう 女性 が 最近 [UNK] 年間 消息 不明な ので 一緒に 彼女 を 探して ほしい 」 と 頼ま れる [UNK] その 帰り ##道 [UNK] 亀井 刑事 は 上野 駅 の トイレ の 中 で 刺殺 体 が 発見 さ れる 事件 に 遭遇 [UNK] その 死体 の 主 は 待ち ##合わせ の 場所 に 来 なかった 安田 章 だった [UNK] 列車 が 仙台 を 過ぎた 頃 [UNK] 町田 が 「 川島 の 姿 が 見え ない 」 と 宮本 を 叩き ##起こす [UNK] 確かに 寝台 の 中 に 川島 は い なかった [UNK] だが [UNK] 川島 が 見つかる こと も なく [UNK] 列車 は 青森 駅 に 到着 する [UNK] 青森 県警 の 三浦 刑事 が [UNK] [UNK] [UNK] 人 は 安田 が 殺さ れた こと を 知ら さ れる [UNK] 当初 [UNK] 川島 が 安田 を 殺害 して 逃亡 した ので は と 思わ れた が [UNK] 川島 は その後 [UNK] 鬼 ##怒 ##川 で 水 ##死 体 で 発見 さ れ [UNK] 自殺 と 思わ れた [UNK] 宮本 ら [UNK] 人 は 青森 県警 本部 で の 事情 聴取 の 後 [UNK] 三浦 刑事 から 青森 市 内 の ホテル に 足 ##止め を 喰 ##らう が [UNK] ホテル の 部屋 で 橋 ##口 ま ##ゆみ が 遺書 を 残して 死亡 する [UNK] 自殺 か と も 思わ れた が 他 ##殺 の 疑い も 濃 ##厚 ##であり [UNK] 青森 県警 の 捜査 も 混 ##迷 を 極め ##る [UNK] 結局 [UNK] 決定 的な 証拠 が 見つから ない まま 県警 の 捜査 本部 は 解散 する が [UNK] 今度 は 青森 駅 の 待合室 で 村上 陽子 が 他 ##殺 体 で 発見 さ れる [UNK] 同じ 頃 [UNK] 東京 でも 上野 署 の 捜査 本部 が 解散 さ れよう と して いた が [UNK] 上野 駅 で 片岡 清 ##之 が 毒殺 さ れた と の 連絡 が 入る [UNK] 最終 的に 旧友 [SEP]
INFO:tensorflow:input_ids: 2 3356 1455 1 494 5 320 396 13 880 76 980 5 1157 166 137 13184 3238 9 1 320 22 87 8 18891 24 1 14 19439 635 5650 13 3356 8 13048 1210 25 12 56 4451 8 6306 1 1 10023 1 29 5 13048 2362 5 327 10 10066 151 5 544 1 50 8 12748 2801 4223 8408 668 1 144 5 17962 12 3644 10 5719 1 355 3785 5016 5 1 26 1 29 1 4260 92 8 9 13184 10 5894 1 50 16 15086 1045 1317 1 16123 1173 2968 1 6607 13694 1 783 1615 1593 31832 1 11749 3514 1792 17 11 2080 10 29429 1920 11 1 2894 1 50 15 10341 1919 9 4223 8408 668 1 144 5 11585 218 8 78 23 4260 92 8 9 4819 116 1 4223 8408 668 1 144 9 1 1 50 11890 47 1 50 10 13901 4260 92 10 3785 20 1 363 1 6811 1040 3234 70 3862 5 20433 3587 9 1 3356 27 5515 20 30354 15 24727 27 24 447 5 18796 32 1779 920 3176 281 12 56 405 11 3677 1 397 14476 17456 314 3353 694 10 12215 7995 25 12 19845 41 1 58 11150 1136 1 20433 3587 9 4260 92 5 6156 5 68 13 30741 254 11 606 18 41 390 8 7235 1 58 8180 5 692 9 6912 14323 5 463 8 1574 116 10341 1919 137 1 515 11 2001 10 14528 349 1 11749 11 24 16123 5 958 11 5758 47 25 12 13184 10 9764 29816 1 18589 12748 5 68 8 16123 9 142 116 1 2041 1 16123 11 23025 30 23 140 1 515 9 3356 92 8 1754 22 1 3356 15378 5 7133 3587 11 1 1 1 50 9 10341 11 4797 28 30 10 302 18 41 1 378 1 16123 11 10341 10 2252 19 5511 20 314 9 12 1578 28 11 1 16123 9 132 1 3505 27134 521 13 404 4844 254 13 606 18 54 1 4181 12 1578 28 1 13184 94 1 50 9 3356 15378 1533 13 5 3348 11995 5 62 1 7133 3587 27 3356 65 76 5 1762 8 1288 10110 10 16439 21407 11 1 1762 5 2102 13 783 1615 1593 31832 11 24867 10 3541 1523 22 1 4181 90 12 23 1578 28 11 151 7896 5 7681 23 7623 12214 2067 1 3356 15378 5 3234 23 5295 31856 10 25499 668 1 2263 1 469 96 4129 11 18158 47 931 15378 5 3234 1533 9 1777 22 11 1 7422 9 3356 92 5 17118 13 6607 13694 11 151 7896 254 13 606 18 41 1 328 349 1 133 123 4260 3288 5 3234 1533 11 1777 18 31088 12 19 37 11 1 4260 92 13 15086 1045 1317 11 23794 18 28 12 5 1956 11 1090 1 549 104 30354 3
I0107 07:20:40.404122 140128358901632 run_classifier_suspection.py:516] input_ids: 2 3356 1455 1 494 5 320 396 13 880 76 980 5 1157 166 137 13184 3238 9 1 320 22 87 8 18891 24 1 14 19439 635 5650 13 3356 8 13048 1210 25 12 56 4451 8 6306 1 1 10023 1 29 5 13048 2362 5 327 10 10066 151 5 544 1 50 8 12748 2801 4223 8408 668 1 144 5 17962 12 3644 10 5719 1 355 3785 5016 5 1 26 1 29 1 4260 92 8 9 13184 10 5894 1 50 16 15086 1045 1317 1 16123 1173 2968 1 6607 13694 1 783 1615 1593 31832 1 11749 3514 1792 17 11 2080 10 29429 1920 11 1 2894 1 50 15 10341 1919 9 4223 8408 668 1 144 5 11585 218 8 78 23 4260 92 8 9 4819 116 1 4223 8408 668 1 144 9 1 1 50 11890 47 1 50 10 13901 4260 92 10 3785 20 1 363 1 6811 1040 3234 70 3862 5 20433 3587 9 1 3356 27 5515 20 30354 15 24727 27 24 447 5 18796 32 1779 920 3176 281 12 56 405 11 3677 1 397 14476 17456 314 3353 694 10 12215 7995 25 12 19845 41 1 58 11150 1136 1 20433 3587 9 4260 92 5 6156 5 68 13 30741 254 11 606 18 41 390 8 7235 1 58 8180 5 692 9 6912 14323 5 463 8 1574 116 10341 1919 137 1 515 11 2001 10 14528 349 1 11749 11 24 16123 5 958 11 5758 47 25 12 13184 10 9764 29816 1 18589 12748 5 68 8 16123 9 142 116 1 2041 1 16123 11 23025 30 23 140 1 515 9 3356 92 8 1754 22 1 3356 15378 5 7133 3587 11 1 1 1 50 9 10341 11 4797 28 30 10 302 18 41 1 378 1 16123 11 10341 10 2252 19 5511 20 314 9 12 1578 28 11 1 16123 9 132 1 3505 27134 521 13 404 4844 254 13 606 18 54 1 4181 12 1578 28 1 13184 94 1 50 9 3356 15378 1533 13 5 3348 11995 5 62 1 7133 3587 27 3356 65 76 5 1762 8 1288 10110 10 16439 21407 11 1 1762 5 2102 13 783 1615 1593 31832 11 24867 10 3541 1523 22 1 4181 90 12 23 1578 28 11 151 7896 5 7681 23 7623 12214 2067 1 3356 15378 5 3234 23 5295 31856 10 25499 668 1 2263 1 469 96 4129 11 18158 47 931 15378 5 3234 1533 9 1777 22 11 1 7422 9 3356 92 5 17118 13 6607 13694 11 151 7896 254 13 606 18 41 1 328 349 1 133 123 4260 3288 5 3234 1533 11 1777 18 31088 12 19 37 11 1 4260 92 13 15086 1045 1317 11 23794 18 28 12 5 1956 11 1090 1 549 104 30354 3
INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [ ]:
# text.tsvで正解率を算出
import csv


with open("test.tsv") as f, open("tmp/suspection_output_predic/test_results.tsv") as rf:
  test = csv.reader(f, delimiter = '\t')
  test_result = csv.reader(rf, delimiter = '\t')

  # 正解データの抽出
  next(test)
  test_list = [int(row[1]) for row in test ]

  # 予測結果を抽出
  result_list = [0 if row[0] > row[1] else 1 for row in test_result ]

  test_count = len(test_list)
  result_correct_answer_list = [result for test, result in zip(test_list, result_list) if test == result]
  result_correct_answer_count = len(result_correct_answer_list)
  print("正解率: ", result_correct_answer_count / test_count)

正解率:  0.8791208791208791